items:
- name: Docker용 Visual Studio Tools
  href: /dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker?toc=/visualstudio/docker/toc.json&bc=/visualstudio/docker/breadcrumb/toc.json
  items:
  - name: 로컬 Docker 컨테이너에서 앱 디버그
    href: ../docker/vs-azure-tools-docker-edit-and-refresh.md
  - name: Visual Studio를 사용하여 컨테이너 레지스트리에 ASP.NET 컨테이너 배포
    href: ../docker/vs-azure-tools-docker-hosting-web-apps-in-docker.md
  - name: Docker 머신을 사용하여 Azure에 Docker 호스트 만들기
    href: ../docker/vs-azure-tools-docker-machine-azure-config.md
  - name: VirtualBox를 사용하여 Docker 호스트 구성
    href: ../docker/vs-azure-tools-docker-setup.md
  - name: Docker 관련 Visual Studio 2017 개발 문제 해결
    href: ../docker/vs-azure-tools-docker-troubleshooting-docker-errors.md
  expanded: true
ms.openlocfilehash: ac508684958e53e65694c3740c291efe4269e6e8
ms.sourcegitcommit: be938c7ecd756a11c9de3e6019a490d0e52b4190
ms.translationtype: HT
ms.contentlocale: ko-KR
ms.lasthandoff: 10/31/2018
ms.locfileid: "50673180"
